# Generated by Django 3.1.1 on 2021-02-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=150, verbose_name='subject')),
                ('models', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Name of Location')),
                ('image', models.ImageField(max_length=25600, upload_to='media/location', verbose_name='Image')),
                ('subject', models.CharField(max_length=150, verbose_name='subject')),
                ('short_describe', models.CharField(max_length=150, verbose_name='Short describe')),
                ('describtion', models.TextField(verbose_name='Details of place')),
            ],
        ),
        migrations.CreateModel(
            name='Subcriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Fullname')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email ID')),
            ],
        ),
    ]
