# Generated by Django 3.1.1 on 2021-02-27 07:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_location_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company name')),
                ('copyright', models.CharField(max_length=150, verbose_name='Copyright')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Company register Email Address')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('office_address', models.CharField(max_length=250, verbose_name='Office Address')),
            ],
        ),
    ]
